### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by arita297** [chgagne/beagle#20]
Hello,

Just wondering if there is a Python wrapping using PyBind 11 ?

Just wondering if this project is maintained ?

Thanks

**Comment by chgagne** [comment]
Hi,

No Python Binding, sorry. If you are interested in doing evolutionary computation in Python, please check DEAP, which is made by the same research group.

https://github.com/DEAP/deap

The project is hardly maintainted. I am way too busy to do anymore coding and there seems nobody interested in handling it, so I am making minimal intendance in order to keep it alive, but still no new developments since several years.

Christian
